do
Dim var1, var2 
var1="LA PUTA MADRE CON TU VIEJA ENSERIO NO CREEERAS LO QUE PASO LA MIERDA DE LAS MIERDAS, PERO JAMAS PARARAS ESTA CABRONADA DE ARCHIVO QUE PENDEJO JA JA ENSERIO NO LO LOGRARAS PERO EN REALIDAD NO SABES UN DATO IMPORTANTE DE LA PUTA MADRE DE TU PUTA Y PUTA HIJO DE PERRA CABRON!!!"
Set va2=CreateObject("sapi.spvoice")
va2.Speak var1
loop
